import type { Metadata } from "next";
import {Header} from "@/components/layout";
import {Toaster} from "react-hot-toast";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />

      {children}

      <Toaster />
    </div>
  );
}
