import type { Metadata } from "next";
import {AccountHeader} from "@/components/layout";
import {cookies} from "next/headers";
import {redirect} from "next/navigation";
import {AccountSidebar} from "@/components/account";
import {Container} from "@/components/ui";

export const metadata: Metadata = {
  title: "Cabinet",
  description: "Generated by create next app",
};

export default async function CabinetLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get('customer_token')?.value;

  if (!token) {
    redirect('/');
  }

  return (
    <div>
      <AccountHeader />

      <Container className="mt-10 flex gap-8">
        <AccountSidebar />

        {children}
      </Container>
    </div>
  );
}
