import type { Metadata } from "next";
import {AccountHeader} from "@/components/layout";

export const metadata: Metadata = {
  title: "Cabinet",
  description: "Generated by create next app",
};

export default function CabinetLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <AccountHeader />

      {children}
    </div>
  );
}
