import type { Metadata } from "next";
import {AccountHeader} from "@/components/layout";
import {AccountSidebar} from "@/components/account";
import {Container} from "@/components/ui";
import {getSession} from "@/lib";
import {redirect} from "next/navigation";

export const metadata: Metadata = {
  title: "Cabinet",
  description: "Generated by create next app",
};

export default async function CabinetLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  if (!session.isAuthenticated) {
    redirect("/");
  }

  return (
    <div>
      <AccountHeader />

      <Container className="mt-10 flex gap-8">
        <AccountSidebar />

        {children}
      </Container>
    </div>
  );
}
